### ISSUE TITLE
安卓端“没有房间”bug

### ISSUE THREAD

**Issue by BlurDelphin** [guyijie1211/JustLive-Android#12]
-  在安卓端，先选中直播平台（比如虎牙），再选择一个分区游戏，如果虎牙的这个游戏没有直播，就会收到“没有房间”的提示。此时再切换回任何一个分区游戏，虎牙都会提示“没有房间”，无法正常观看。

- 另外希望完善下虎牙的其它一些游戏直播，比如荒野大镖客之类的，实际上是有人在直播的，但就是看不了

**Comment by guyijie1211** [comment]
0.2.2已修复
