### ISSUE TITLE
一些建议以及想法

### ISSUE THREAD

**Issue by WarwickJiang** [guyijie1211/JustLive-Android#14]
希望可以完善斗鱼平台的主播搜索系统。
能否对应该直播间自身清晰度设置自动匹配对应的清晰度选项（例如z直播）
您的这款软件b站的清晰度相比z很优秀，如果能日渐完善，我会选择使用他的

**Comment by guyijie1211** [comment]
斗鱼的搜索有限流，后面会想办法解决
清晰度这个我感觉问题不大，暂时就这样吧
