### ISSUE TITLE
求出個TV版..手機不看直播.

### ISSUE THREAD

**Issue by mk2leo** [guyijie1211/JustLive-Android#17]
求出個TV版..手機不看直播.

**Comment by drw2005** [comment]
希望大佬考虑啊，TV版太需要了。

**Comment by Afire-625** [comment]
> 希望大佬考虑啊，TV版太需要了。

TV版不是可以利用浏览器到其网页实现观看吗

**Comment by drw2005** [comment]
> > 希望大佬考虑啊，TV版太需要了。
> 
> TV版不是可以利用浏览器到其网页实现观看吗

哪有专业的TV版本用着爽快啊。

**Comment by qianfanguojin** [comment]
虎牙和斗鱼都有TV版本吧
