### ISSUE TITLE
v0.2.3bug反馈

### ISSUE THREAD

**Issue by ljqyyds123** [guyijie1211/JustLive-Android#19]
v0.2.3
app在横屏（平板电脑，电视）情况下在设置里选择进入直播间时全屏，在进入直播间时会从原本的初始横屏（非全屏状态）自动切换成竖屏方式的全屏（非常怪异）而不是进入横屏全屏模式（手动点击全屏图标进入全屏模式正常）。

**Comment by ioeysn** [comment]
弹幕有问题，同时打开斗鱼和justlive，对比弹幕，justlive弹幕中会出现有很多原直播间不存在的弹幕发出，例如这两天在看斗鱼的主播孙悟空和余小c玩老头环，用justlive看的时候弹幕中总会有一些英雄联盟相关的弹幕，而斗鱼却没有。直接看图吧，
![Screenshot_20220305_125130_air tv douyu android](https://user-images.githubusercontent.com/98942421/156868539-a458cc44-c7a7-48cf-97c3-25e820a539b0.jpg)
![Screenshot_20220305_125130_air tv douyu android](https://user-images.githubusercontent.com/98942421/156868542-602bc952-d084-42d7-a62e-352e2da48759.jpg)
红色就是不存在的弹幕

**Comment by ioeysn** [comment]
会出现一些不存在的弹幕，红色就是，直接看图把
![Screenshot_20220305_125130_air tv douyu android](https://user-images.githubusercontent.com/98942421/156868589-d0641486-9790-4ce7-b003-0b20816463b3.jpg)
![Screenshot_20220305_125106_com yj1211 justlive_edit_150972981186337](https://user-images.githubusercontent.com/98942421/156868591-6558df3c-a03e-4011-bd04-90bbb5da8c4c.jpg)
