### ISSUE TITLE
justlive_0.2.3 bug

### ISSUE THREAD

**Issue by Bonnie-Ran** [guyijie1211/JustLive-Android#24]
设备: Android 9(MIUI 10)

1. 关注的虎牙主播未开播时不显示在未开播列表，斗鱼和哔哩哔哩正常(例如*张大仙*/*沫子*等，上个版本貌似没有这个问题);
2. 弹幕偶尔会出现抖动，持续几秒恢复正常(不知道你那边能不能复现);
3. 外置播放器直接调用下载管理(是*MIUI*的锅还是bug)，禁用后才会出现第三方播放器的选项(例如*MX Player*等);
4. ~~全屏观看直播，点击通知栏别的APP消息，不会出现小窗，再点击进直播间黑屏，退出直播间软件重新加载，[捕获的日志](https://wws.lanzouv.com/i5FWR01j9umh) 密码: live;~~
5. 打开定时关闭开关，再次查看按钮显示关闭，如同时打开总是开启按钮则不会显示关闭;
6. 软件内打开/关闭夜间模式，直播中/未开播列表空白，退出软件重进恢复正常;

PS: 看到issues了，4已修复，辛苦开发者，软件做的很棒！！！

**Comment by guyijie1211** [comment]
1. 0.2.5已修复
2. 最好能提供复现方法
3. 我也是miui，没有遇到这个问题
5/6. 有空修一下
