### ISSUE TITLE
哔哩哔哩直播加载不出

### ISSUE THREAD

**Issue by loa123** [guyijie1211/JustLive-Android#36]
是不是接口没了？只有弹幕，画面加载出错![Screenshot_20220610_184704_com.yj1211.justlive.jpg](https://user-images.githubusercontent.com/4455716/173049356-f1eadd0c-3e75-4111-8d58-28e4766b40c2.jpg)

**Comment by cloovver** [comment]
加一 ，弹幕能出，但是图像出不来
