### ISSUE TITLE
虎牙所有直播都无法观看

### ISSUE THREAD

**Issue by JohnFrankz** [guyijie1211/JustLive-Android#50]
打开任意虎牙直播，都出现黑屏只有弹幕的情况。
![Screenshot_2023-02-07-13-04-04-116_com.yj1211.justlive.jpg](https://user-images.githubusercontent.com/86246881/217153224-7660a3da-58c7-442c-aacc-17dfd027665c.jpg)

**Comment by A3148475824** [comment]
纯粹直播可以用

**Comment by hean2002** [comment]
确实，看不了
